export const actionType = {
  FETCH_PRODUCT_DATA_SUCCESS: "FETCH_PRODUCT_DATA_SUCCESS",
  FETCH_PRODUCT_DATA_FAILURE: "FETCH_PRODUCT_DATA_FAILURE",
  FETCH_PRODUCT_DATA_LOADING: "FETCH_PRODUCT_DATA_LOADING",
}